apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wq2imay85-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:df404ac2814cbe246dd13379c2673c8112cafd3b@sha256:1f4fea424deb9d05f1289b6ab25a1bdb092994a1ea3349650d4eaed0217bc5e7
          name: container-image
